tunnel: <tunnel-id>
credentials-file: /home/nonroot/.cloudflared/<tunnel-id>.json
protocol: http2

ingress:
  - hostname: app.example.com
    service: http://service-1:8080
  - service: http_status:404
