services:
 cloudflare:
    image: "cloudflare/cloudflared:2024.11.1"
    container_name: "cloudflare"
    volumes: ['./web/prod:/home/nonroot/.cloudflared']
    command: tunnel run
    restart: unless-stopped
